spring.application.name=blogproject

spring.thymeleaf.cache=false
spring.data.mongodb.uri=${MONGODB_URI}
spring.data.mongodb.database=galeria
sightengine.api-user=1606926100
sightengine.api-secret=MBzEjBL2cbpnxMzqBYKJCQHRNo3CFRVx